import type { LifecycleMoney, WorkerOperationalPhase } from './model';

export const WORKER_LIFECYCLE_SOURCE_LOCALE = 'en-ZA' as const;

const MESSAGES = Object.freeze({
  'common.back': 'Back',
  'common.retry': 'Try again',
  'common.refresh': 'Refresh',
  'common.save': 'Save changes',
  'common.cancel': 'Cancel',
  'common.continue': 'Continue',
  'common.viewDetails': 'View details',
  'common.notAvailable': 'Not available',
  'common.offline': 'You’re offline. Saved details remain visible, but live changes are paused.',
  'common.lastUpdated': 'Last updated {time}',
  'activation.title': 'Worker setup',
  'activation.heading': 'Get ready to take jobs',
  'activation.body': 'Each required item must be backed by server evidence before you can go online.',
  'activation.progress': '{complete} of {total} required items complete',
  'activation.public': 'Public profile requirements',
  'activation.private': 'Private readiness requirements',
  'activation.complete': 'Complete',
  'activation.incomplete': 'Action required',
  'activation.failed': 'Needs attention',
  'activation.pending': 'Review in progress',
  'activation.notRequired': 'Not required',
  'activation.openItem': 'Resolve this item',
  'activation.actionUnavailable': 'No version-matched completion action is enabled in this APK. Follow the guidance above and refresh after the protected flow becomes available.',
  'activation.onlineReady': 'Ready to request Online',
  'activation.openAvailability': 'Open availability',
  'activation.loadErrorTitle': 'Setup could not be loaded',
  'activation.loadErrorBody': 'No readiness or availability state was changed.',
  'service.title': 'Services and public profile',
  'service.catalogueFacts': 'Catalogue facts',
  'service.catalogueReadOnly': 'Category, service version, pricing mode, risk tier, credential requirements and fixed-payout rules are controlled by the catalogue.',
  'service.choose': 'Choose a service to edit',
  'service.emptyTitle': 'No services available',
  'service.emptyBody': 'A server-confirmed eligible service is required before an offering can be created.',
  'service.customerTitle': 'Customer-facing title',
  'service.description': 'Service description',
  'service.hourlyRate': 'Hourly rate in rand',
  'service.minimumDuration': 'Minimum duration in minutes',
  'service.callOut': 'Call-out amount in rand',
  'service.area': 'Service area',
  'service.credentials': 'Credential evidence',
  'service.portfolio': 'Portfolio evidence',
  'service.active': 'Service active',
  'service.activeBody': 'Only the server-confirmed state controls whether customers can discover this service.',
  'service.save': 'Save service',
  'service.toggleOn': 'Request service activation',
  'service.toggleOff': 'Request service deactivation',
  'service.failedRollback': 'The save failed. The last server-confirmed values remain active.',
  'profile.publicPreview': 'Current public preview',
  'profile.publicFields': 'Public fields',
  'profile.privateFields': 'Private account fields',
  'profile.about': 'About and experience',
  'profile.photo': 'Public profile photo',
  'profile.replacePhoto': 'Replace profile photo',
  'profile.uploading': 'Uploading photo: {progress}%',
  'profile.badges': 'Evidence-backed badges',
  'profile.noBadgeEvidence': 'No public badge evidence is available.',
  'profile.save': 'Save public profile',
  'profile.privateBody': 'Payout, contact and emergency details never appear in the public preview.',
  'job.title': 'Worker Job',
  'job.currentState': 'Current phase',
  'job.timeline': 'Job timeline',
  'job.customer': 'Customer',
  'job.schedule': 'Schedule',
  'job.location': 'Job location',
  'job.contact': 'Permitted contact',
  'job.scope': 'Agreed scope',
  'job.earnings': 'Expected job earnings',
  'job.gross': 'Gross job amount',
  'job.fee': 'Platform fee',
  'job.net': 'Expected net',
  'job.navigation': 'Open navigation',
  'job.chat': 'Chat',
  'job.safety': 'Safety and help',
  'job.detailsShow': 'Show Job details',
  'job.detailsHide': 'Hide Job details',
  'job.unknownTitle': 'Job state needs review',
  'job.unknownBody': 'This phase is not recognised by this app. Details remain read-only and Safety/Help stays available.',
  'tracking.title': 'Location sharing',
  'tracking.hidden': 'Location sharing is hidden outside the approved operational window.',
  'tracking.notStarted': 'Location sharing has not started.',
  'tracking.sharing': 'Foreground job location is being shared for this active route.',
  'tracking.stale': 'Location sharing is stale. Reconnect before relying on route progress.',
  'tracking.failed': 'Location could not be shared. Other Job actions remain available.',
  'tracking.stopped': 'Location sharing has stopped for this Job.',
  'privacy.broadOnly': 'Only the broad area is available until Start route or the approved lead-time window.',
  'privacy.exact': 'Exact address is available for the authorised operational window.',
  'privacy.masked': 'Contact details remain masked for this phase.',
  'scope.title': 'Scope and Job start',
  'scope.acceptedBrief': 'Accepted brief version {version}',
  'scope.version': 'On-site scope version {version}',
  'scope.included': 'Included work',
  'scope.excluded': 'Excluded work',
  'scope.checklist': 'On-site checklist',
  'scope.materials': 'Materials responsibility',
  'scope.timeRate': 'Time and rate',
  'scope.totalCap': 'Total or approval cap',
  'scope.workerConfirmation': 'Worker confirmation',
  'scope.customerConfirmation': 'Customer confirmation',
  'scope.confirm': 'Confirm current scope',
  'scope.requestRevision': 'Request a scope revision',
  'scope.clarification': 'Clarification or requested revision',
  'scope.pin': 'Customer start PIN',
  'scope.pinEntry': 'Enter the PIN shared by the customer',
  'scope.pinPrivate': 'The correct PIN is never revealed on the Worker screen.',
  'scope.verifyPin': 'Verify PIN and start once',
  'scope.attempts': '{count} attempts remaining',
  'scope.noSkip': 'Scope confirmation and the customer PIN are required. There is no skip action.',
  'scope.started': 'Job start confirmed',
  'scope.startedBody': 'Actor, device and server timestamps are recorded for this start.',
  'work.title': 'Active work',
  'work.scopeVersion': 'Current agreed scope version {version}',
  'work.elapsed': 'Elapsed time',
  'work.currentTotal': 'Current approved total',
  'work.approvalCap': 'Customer approval cap',
  'work.currentNet': 'Current expected net',
  'work.changes': 'Change orders',
  'work.noChanges': 'No change orders have been recorded.',
  'work.requestExtra': 'Request extra work',
  'work.description': 'Additional work description',
  'work.addedTime': 'Added time in minutes',
  'work.materials': 'Additional materials',
  'work.additionalAmount': 'Additional customer amount in rand',
  'work.preview': 'Server preview',
  'work.revisedTotal': 'Revised customer total',
  'work.additionalNet': 'Expected additional net',
  'work.pendingWarning': 'Pending work and money are not part of the agreement until the customer approves them.',
  'work.submitChange': 'Send change for approval',
  'work.requestCompletion': 'Request completion review',
  'completion.title': 'Completion and issues',
  'completion.scope': 'Final scope',
  'completion.evidence': 'Completion evidence',
  'completion.payment': 'Customer payment state',
  'completion.net': 'Expected job net',
  'completion.issue': 'Open issue',
  'completion.support': 'Open issue support',
  'completion.request': 'Request customer completion review',
  'completion.bilateral': 'The customer confirms, disputes or reaches the disclosed timeout outcome. A Worker request never closes the Job by itself.',
  'completion.separateMoney': 'Payment, rating eligibility and payout eligibility remain separate server states.',
  'account.title': 'Worker account',
  'account.heading': 'Account and readiness',
  'account.progress': '{ready} sections ready · {action} need action',
  'account.public': 'Public identity and services',
  'account.private': 'Private settings and support',
  'account.unavailable': 'This section is unavailable: {reason}',
  'account.open': 'Open section',
  'account.support': 'Support and safety',
  'account.signOut': 'Sign out',
  'state.loading': 'Loading the latest server state',
  'state.empty': 'No server state is available.',
  'state.errorTitle': 'This information could not be loaded',
  'state.errorBody': 'No authoritative state was changed. Try again.',
} as const);

export type WorkerLifecycleMessageKey = keyof typeof MESSAGES;
export type WorkerLifecycleMessageValues = Readonly<Record<string, string | number>>;

const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9]*)\}/g;

export function workerLifecycleMessage(
  key: WorkerLifecycleMessageKey,
  values: WorkerLifecycleMessageValues = {},
): string {
  return MESSAGES[key].replace(PLACEHOLDER, (_match, name: string) => {
    const value = values[name];
    if (value === undefined) throw new Error(`Missing Worker lifecycle message value: ${name}`);
    return String(value);
  });
}

const ZAR = new Intl.NumberFormat(WORKER_LIFECYCLE_SOURCE_LOCALE, {
  style: 'currency',
  currency: 'ZAR',
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
});

export function formatLifecycleMoney(value: LifecycleMoney | null): string {
  return value
    && value.currency === 'ZAR'
    && Number.isSafeInteger(value.amountMinor)
    && value.amountMinor >= 0
    ? ZAR.format(value.amountMinor / 100)
    : workerLifecycleMessage('common.notAvailable');
}

export function workerPhaseLabel(phase: WorkerOperationalPhase): string {
  return {
    accepted: 'Accepted',
    scheduled: 'Scheduled',
    en_route: 'En route',
    arrived: 'Arrived',
    scope_confirmation: 'Scope confirmation',
    work_active: 'Work active',
    completion_review: 'Completion review',
    payment_pending: 'Payment pending',
    closed: 'Closed',
    cancelled: 'Cancelled',
    unknown: 'Unknown phase',
  }[phase];
}
