import { SOURCE_LOCALE, formatZarEnZa } from '../../../i18n/en-ZA';

export const CUSTOMER_INTAKE_LOCALE = SOURCE_LOCALE;

export const CUSTOMER_INTAKE_MESSAGES = Object.freeze({
  'common.back': 'Back',
  'common.continue': 'Continue',
  'common.edit': 'Edit',
  'common.retry': 'Try again',
  'common.saveDraft': 'Save draft',
  'common.yes': 'Yes',
  'common.no': 'No',
  'home.account': 'Open account',
  'home.location': 'Job location',
  'home.locationFallback': 'Choose a job location',
  'home.title': 'What needs doing?',
  'home.intentLabel': 'Describe the job in your own words',
  'home.intentHint': 'For example: Fix a leaking tap in the kitchen.',
  'home.intentHelper': 'A short description helps us suggest the right service. It does not check worker availability.',
  'home.camera': 'Add a photo',
  'home.cameraHint': 'Opens the job brief photo step.',
  'home.voice': 'Use voice',
  'home.voiceHint': 'Describe the job using the available assisted intake service.',
  'home.suggestions': 'Suggested services',
  'home.suggestionsBody': 'Suggestions come from the service catalogue, not live worker availability.',
  'home.services': 'Service shortcuts',
  'home.servicesBody': 'Start a prefilled job brief.',
  'home.activeProject': 'Current project',
  'home.recentWorkers': 'Recent workers',
  'home.continue': 'Start job brief',
  'home.noServices': 'No service suggestions yet',
  'home.noServicesBody': 'Keep describing the job or choose a service shortcut below.',
  'home.offline': 'You can write and save a job draft. Reconnect before sending it.',
  'home.capabilityUnavailable': '{feature} is not available. {reason}',
  'home.relationshipsUnavailable': 'Favourite and book-again actions stay hidden until relationships are available.',
  'brief.title': 'Tell us about the job',
  'brief.progress': 'Step {current} of {total}: {step}',
  'brief.need': 'Need',
  'brief.details': 'Details',
  'brief.photos': 'Photos',
  'brief.responsibility': 'Materials',
  'brief.estimate': 'Estimate',
  'brief.summary': 'Your job brief',
  'brief.required': 'Required',
  'brief.optional': 'Optional',
  'brief.notNeeded': 'Not needed',
  'brief.addPhoto': 'Add photo',
  'brief.photoUnavailable': 'Photo attachment is not available. You can continue if photos are optional.',
  'brief.photosNotUsed': 'Photos are not needed for this service version.',
  'brief.uploadLocal': 'Saved with this draft',
  'brief.cropping': 'Preparing crop…',
  'brief.compressing': 'Compressing photo: {progress}%',
  'brief.uploading': 'Uploading: {progress}%',
  'brief.uploaded': 'Ready',
  'brief.uploadFailed': 'Upload failed',
  'brief.retryPhoto': 'Retry photo',
  'brief.removePhoto': 'Remove photo',
  'brief.materialsTitle': 'Who should provide materials or parts?',
  'brief.materialsCustomer': 'I will provide them',
  'brief.materialsWorker': 'The worker should provide them',
  'brief.materialsDiscuss': 'Discuss this with the worker',
  'brief.budget': 'Maximum budget in rand',
  'brief.diagnosticNeed': 'What should the diagnostic visit establish?',
  'brief.modeExplanation': 'Why this job uses {mode}',
  'brief.offline': 'This draft can be saved offline, but it cannot be sent until you reconnect.',
  'address.appBar': 'Job location',
  'address.title': 'Confirm the job address',
  'address.privacy': 'Workers see only the broad area until the approved route-start window.',
  'address.savedPlaces': 'Saved places',
  'address.search': 'Search for an address',
  'address.searchHint': 'Start with the street address, suburb or place name.',
  'address.searchResults': 'Address suggestions',
  'address.searching': 'Looking for matching addresses…',
  'address.currentLocation': 'Use current location',
  'address.currentLocationHint': 'Requires device location and canonical address verification before it can be confirmed.',
  'address.map': 'Map and pin',
  'address.locationDetails': 'Address details',
  'address.locationDetailsBody': 'Enter the address the worker will use to reach the job.',
  'address.manualTitle': 'Enter the address manually',
  'address.line1': 'Street address',
  'address.unit': 'Complex, estate, building or unit',
  'address.suburb': 'Suburb',
  'address.city': 'City or town',
  'address.province': 'Province',
  'address.postalCode': 'Postal code',
  'address.landmark': 'Nearby landmark',
  'address.access': 'Access, parking or gate instructions',
  'address.resolve': 'Resolve this address',
  'address.resolveHint': 'Gets operational coordinates while keeping your entered instructions.',
  'address.correctPin': 'Correct the pin',
  'address.exactLocation': 'Exact job location',
  'address.exactLocationBody': 'Place a pin so the worker can reach the correct property, entrance or building.',
  'address.pinReady': 'Exact pin set',
  'address.pinReadyBody': 'This pin is paired with the address above. Workers still see only the broad area until the approved route-start window.',
  'address.pinMissing': 'Exact pin still needed',
  'address.setPin': 'Set exact pin',
  'address.setPinHint': 'Opens a dedicated map where you can position and accept the exact job pin.',
  'address.adjustPin': 'Adjust pin',
  'address.adjustPinHint': 'Opens the map without changing the saved pin unless you accept a new position.',
  'address.pinNeedsAddress': 'Add the street address, city or town, and province before setting the pin.',
  'address.arrivalNotes': 'Arrival notes',
  'address.arrivalNotesBody': 'Optional details stay private with the exact job address.',
  'address.coordinatesReady': 'Coordinates confirmed',
  'address.coordinatesUnverified': 'Coordinates are not verified for dispatch',
  'address.coordinatesUnverifiedBody': 'These coordinates are not linked to the displayed address. Save the draft, then retry with provider address resolution, a verified saved place or an integrated map pin.',
  'address.coordinatesMissing': 'Coordinates are still needed before dispatch',
  'address.coordinatesMissingBody': 'Save the draft now, then retry provider address resolution, use a verified saved place or use an integrated map pin when available.',
  'address.mapUnavailable': 'The map is unavailable. Complete the manual address path below.',
  'address.confirm': 'Confirm address',
  'address.offline': 'You can edit and save this address offline. Coordinate resolution and dispatch need a connection.',
  'schedule.title': 'When should the work happen?',
  'schedule.now': 'Now',
  'schedule.nowBody': 'Start matching after the job is confirmed.',
  'schedule.scheduled': 'Schedule',
  'schedule.scheduledBody': 'Choose a future date and time.',
  'schedule.timezone': 'Times use South Africa Standard Time (Africa/Johannesburg).',
  'schedule.changeTime': 'Choose date and time',
  'schedule.selectedTime': 'Selected time',
  'schedule.duration': 'Estimated duration',
  'schedule.fulfilment': 'How should TOGT fulfil this job?',
  'schedule.fastMatch': 'Fast Match',
  'schedule.fastMatchBody': 'Send a truthful timed offer to eligible workers. This does not time your checkout.',
  'schedule.compareWorkers': 'Compare workers',
  'schedule.compareWorkersBody': 'Review eligible workers, then send a request. A request is not a confirmation.',
  'schedule.receiveQuotes': 'Receive quotes',
  'schedule.receiveQuotesBody': 'Ask workers for complete scope, exclusions, schedule and price.',
  'schedule.diagnosticVisit': 'Book diagnostic visit',
  'schedule.diagnosticVisitBody': 'Book an assessment with a stated deliverable. Later work is separate.',
  'schedule.unavailable': 'Not available for this service',
  'schedule.invalidPast': 'Choose a time later than now.',
  'schedule.continue': 'Review job',
  'review.title': 'Review your job',
  'review.service': 'Service and brief',
  'review.notProvided': 'Not provided yet',
  'review.briefDescription': 'Job description',
  'review.attachments': '{count} photo attachments',
  'review.address': 'Address',
  'review.schedule': 'Schedule',
  'review.fulfilment': 'Fulfilment',
  'review.estimate': 'Estimate',
  'review.payment': 'Payment method and assurance',
  'review.paymentNotRequired': 'No payment is required to send this quote request.',
  'review.labour': 'Labour',
  'review.platformFee': 'Platform fee',
  'review.total': 'All-in total',
  'review.hourlyRate': 'Hourly rate',
  'review.estimatedHours': 'Estimated hours',
  'review.estimatedRange': 'Estimated total range',
  'review.approvalCap': 'Approval cap',
  'review.requestFee': 'Quote request fee',
  'review.noRequestFee': 'No quote request fee',
  'review.quotePending': 'No final total exists until you accept a complete quote.',
  'review.diagnosticFee': 'Diagnostic visit',
  'review.diagnosticDeliverable': 'Visit deliverable',
  'review.laterWorkSeparate': 'Repair or follow-on work is not included.',
  'review.materials': 'Materials assumption',
  'review.cancellation': 'Cancellation terms',
  'review.blocked': 'This job cannot be sent yet',
  'review.confirmFixed': 'Confirm and find a worker',
  'review.confirmHourly': 'Authorise cap and continue',
  'review.confirmQuote': 'Request quotes',
  'review.confirmDiagnostic': 'Confirm diagnostic visit',
  'review.immutable': 'Confirmation locks a versioned snapshot of these terms.',
  'review.offlineSave': 'Save draft on this device',
  'review.submitting': 'Sending job…',
} as const);

export type CustomerIntakeMessageKey = keyof typeof CUSTOMER_INTAKE_MESSAGES;
export type CustomerIntakeInterpolation = Readonly<Record<string, string | number>>;
export type CustomerIntakeTranslate = (
  key: CustomerIntakeMessageKey,
  interpolation?: CustomerIntakeInterpolation,
) => string;

const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9]*)\}/g;

export const translateCustomerIntake: CustomerIntakeTranslate = (
  key,
  interpolation = {},
) => CUSTOMER_INTAKE_MESSAGES[key].replace(PLACEHOLDER, (_match, placeholder: string) => {
  const value = interpolation[placeholder];
  if (value === undefined) throw new Error(`Missing customer intake copy value: ${placeholder}`);
  return String(value);
});

export function formatZarMinor(amountMinor: number): string {
  if (!Number.isSafeInteger(amountMinor) || amountMinor < 0) {
    throw new TypeError('A non-negative whole-cent ZAR amount is required');
  }
  return formatZarEnZa(amountMinor / 100);
}
